# Generated by Django 3.2 on 2021-05-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome exibido na página inicial', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitulo exibido abaixo do nome', max_length=255, null=True)),
                ('summary', models.CharField(blank=True, help_text='Resumo', max_length=2000, null=True)),
                ('background_image', models.CharField(blank=True, help_text='Imagem do fundo da pagina', max_length=255, null=True)),
                ('cover_image', models.CharField(blank=True, help_text='Imagem do card', max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, help_text='Imagem de perfil', max_length=255, null=True)),
                ('blog_button', models.BooleanField(default=True)),
                ('portfolio_button', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Classe do icone do link', max_length=255)),
                ('url', models.CharField(help_text='Url de destino do link', max_length=255)),
                ('alt', models.CharField(help_text='Texto do link', max_length=255)),
                ('order', models.DecimalField(decimal_places=0, max_digits=3)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da postagem', max_length=255)),
                ('slug', models.CharField(help_text='Slug', max_length=255)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('plain_text', models.CharField(help_text='Conteúdo em texto', max_length=255)),
                ('markdown_text', models.CharField(help_text='Conteúdo em markdown', max_length=255)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do projeto', max_length=255)),
                ('description', models.CharField(help_text='Descrição do projeto', max_length=2000)),
                ('image', models.CharField(help_text='Imagem do projeto', max_length=255)),
                ('technologies', models.CharField(blank=True, help_text='Tecnologias utilizadas', max_length=255, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Texto do link', max_length=255)),
                ('icon', models.CharField(help_text='Classe do icone do link', max_length=2000)),
                ('url', models.CharField(help_text='Url de destino do link', max_length=255)),
                ('show', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
