# Generated by Django 3.2 on 2021-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagelink',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AlterModelOptions(
            name='projectlink',
            options={'ordering': ['-project']},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumo', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='markdown_text',
            field=models.TextField(help_text='Conteúdo em markdown'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plain_text',
            field=models.TextField(help_text='Conteúdo em texto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Descrição do projeto', max_length=2000),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='icon',
            field=models.CharField(help_text='Classe do icone do link', max_length=255),
        ),
    ]
