# Generated by Django 3.2 on 2021-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210517_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagem do fundo da pagina', null=True, upload_to='background'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagem do card', null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagem de perfil', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plain_text',
            field=models.TextField(editable=False, help_text='Conteúdo em texto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do projeto', null=True, upload_to='projects'),
        ),
    ]
