# Generated by Django 3.2.7 on 2021-09-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210530_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(editable=False, help_text='Slug', max_length=255),
        ),
    ]
